version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:password@db/gestao_alunos
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gestao_alunos
    volumes:
      - db_data:/var/lib/mysql
      - ./database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge

